language: python
sudo: true
python:
  - "2.7"
  # - "2.6"

services:
  - mongodb

# command to install dependencies
# some are only used for travis/coveralls so we are installing them here only
install:
  - bash test/setup_test.sh

script:
  - cd test
  - pip freeze
  # - nosetests -xv --process-restartworker --processes=1 --process-timeout=300 --with-coverage --cover-package=module test*.py
  # - coverage combine
  # - coverage report -m
  - cd ..

after_success:
  # to get coverage data with relative paths and not absolute we have to
  # execute coveralls from the base directory of the project,
  # so we need to move the .coverage file here :
  mv test/.coverage . && coveralls --rcfile=test/.coveragerc -v
